FROM node:24-alpine
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY --chown=node:node . .
RUN chown -R node:node /app
USER node

EXPOSE 3000
ENV NEXT_TELEMETRY_DISABLED=1
CMD ["node", "node_modules/next/dist/bin/next", "dev", "--hostname", "0.0.0.0"]
