import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('Бастапқы деректерді жүктеу...');

  const hash = async (pw: string) => bcrypt.hash(pw, 12);

  // ── Users ────────────────────────────────────────────────────
  await prisma.user.upsert({
    where: { email: 'admin@proctolearn.kz' },
    update: {},
    create: { name: 'Администратор', email: 'admin@proctolearn.kz', phone: '+77001110000', password: await hash('Admin@12'), role: 'ADMIN' },
  });

  const teacher = await prisma.user.upsert({
    where: { email: 'teacher@proctolearn.kz' },
    update: {},
    create: { name: 'Системный преподаватель', email: 'teacher@proctolearn.kz', phone: '+77002220000', password: await hash('Teach@12'), role: 'TEACHER' },
  });

  await prisma.user.upsert({
    where: { email: 'student@proctolearn.kz' },
    update: {},
    create: { name: 'Студент Алибек', email: 'student@proctolearn.kz', phone: '+77003330000', password: await hash('Stud@123'), role: 'STUDENT' },
  });

  await prisma.user.upsert({
    where: { email: 'proctor@proctolearn.kz' },
    update: {},
    create: { name: 'Проктор Бауыржан', email: 'proctor@proctolearn.kz', phone: '+77004440000', password: await hash('Proct@12'), role: 'PROCTOR' },
  });

  // ── Courses + Lessons ────────────────────────────────────────
  const coursesData = [
    {
      title: 'HTML и CSS с нуля',
      description: 'Основы веб-разработки: структура страниц, стилизация, flexbox и grid. Создашь свою первую веб-страницу с нуля.',
      lessons: [
        { order: 1,  title: 'Что такое HTML и как работает браузер',  content: 'Видеоурок: Что такое HTML и как работает браузер' },
        { order: 2,  title: 'Основные теги: заголовки, параграфы, ссылки', content: 'Видеоурок: Основные теги — заголовки, параграфы, ссылки' },
        { order: 3,  title: 'Списки, таблицы и формы',                content: 'Видеоурок: Списки, таблицы и формы в HTML' },
        { order: 4,  title: 'Читать: шпаргалка по HTML тегам',        content: 'Материал для чтения: шпаргалка по HTML тегам' },
        { order: 5,  title: 'Квиз: структура HTML документа',         content: 'Проверь себя: структура HTML документа' },
        { order: 6,  title: 'Что такое CSS и способы подключения',    content: 'Видеоурок: Что такое CSS и способы подключения' },
        { order: 7,  title: 'Селекторы, цвета и шрифты',             content: 'Видеоурок: Селекторы, цвета и шрифты в CSS' },
        { order: 8,  title: 'Блочная модель (box model)',             content: 'Видеоурок: Блочная модель CSS (box model)' },
        { order: 9,  title: 'Flexbox — практика',                    content: 'Видеоурок: Flexbox на практике' },
        { order: 10, title: 'Задание: верстка карточки профиля',      content: 'Задание: сверстай карточку профиля используя HTML и CSS' },
      ],
    },
    {
      title: 'JavaScript для начинающих',
      description: 'Основы языка JavaScript: переменные, функции, циклы, работа с DOM. Научишься делать страницы интерактивными.',
      lessons: [
        { order: 1,  title: 'Что такое JavaScript и где он работает',  content: 'Видеоурок: Что такое JavaScript и где он работает' },
        { order: 2,  title: 'Переменные: var, let, const',             content: 'Видеоурок: Переменные — var, let, const' },
        { order: 3,  title: 'Типы данных и операторы',                 content: 'Видеоурок: Типы данных и операторы в JavaScript' },
        { order: 4,  title: 'Условия: if/else и switch',               content: 'Видеоурок: Условия — if/else и switch' },
        { order: 5,  title: 'Квиз: переменные и типы данных',          content: 'Проверь себя: переменные и типы данных' },
        { order: 6,  title: 'Циклы: for, while, for...of',             content: 'Видеоурок: Циклы — for, while, for...of' },
        { order: 7,  title: 'Функции: объявление и стрелочные',        content: 'Видеоурок: Функции — объявление и стрелочные' },
        { order: 8,  title: 'Массивы и методы массивов',               content: 'Видеоурок: Массивы и методы массивов' },
        { order: 9,  title: 'Основы работы с DOM',                     content: 'Видеоурок: Основы работы с DOM' },
        { order: 10, title: 'Читать: документация MDN по JS',          content: 'Материал для чтения: документация MDN по JavaScript' },
        { order: 11, title: 'Задание: калькулятор на чистом JS',       content: 'Задание: создай калькулятор на чистом JavaScript' },
      ],
    },
    {
      title: 'Python: первые шаги',
      description: 'Введение в программирование на Python. Переменные, условия, циклы, функции и работа со строками — всё с нуля.',
      lessons: [
        { order: 1, title: 'Установка Python и первая программа',       content: 'Видеоурок: Установка Python и первая программа' },
        { order: 2, title: 'Переменные, типы данных, input/print',      content: 'Видеоурок: Переменные, типы данных, input и print' },
        { order: 3, title: 'Условные операторы if/elif/else',           content: 'Видеоурок: Условные операторы if/elif/else' },
        { order: 4, title: 'Циклы for и while',                        content: 'Видеоурок: Циклы for и while в Python' },
        { order: 5, title: 'Квиз: базовый синтаксис Python',           content: 'Проверь себя: базовый синтаксис Python' },
        { order: 6, title: 'Функции: def, return, параметры',          content: 'Видеоурок: Функции — def, return, параметры' },
        { order: 7, title: 'Списки и словари',                         content: 'Видеоурок: Списки и словари в Python' },
        { order: 8, title: 'Работа со строками',                       content: 'Видеоурок: Работа со строками в Python' },
        { order: 9, title: 'Задание: угадай число (игра)',              content: 'Задание: напиши игру "Угадай число" на Python' },
      ],
    },
    {
      title: 'Git и GitHub с нуля',
      description: 'Система контроля версий Git — основа работы любого разработчика. Научишься работать с ветками, коммитами и GitHub.',
      lessons: [
        { order: 1, title: 'Зачем нужен Git и как он устроен',           content: 'Видеоурок: Зачем нужен Git и как он устроен' },
        { order: 2, title: 'Установка и базовая настройка Git',          content: 'Видеоурок: Установка и базовая настройка Git' },
        { order: 3, title: 'git init, add, commit — первый репозиторий', content: 'Видеоурок: git init, add, commit — первый репозиторий' },
        { order: 4, title: 'Читать: шпаргалка команд Git',              content: 'Материал для чтения: шпаргалка команд Git' },
        { order: 5, title: 'Ветки: создание, переключение, слияние',    content: 'Видеоурок: Ветки — создание, переключение, слияние' },
        { order: 6, title: 'Работа с GitHub: push, pull, clone',        content: 'Видеоурок: Работа с GitHub — push, pull, clone' },
        { order: 7, title: 'Pull Request и Code Review',                content: 'Видеоурок: Pull Request и Code Review' },
        { order: 8, title: 'Квиз: команды Git',                        content: 'Проверь себя: команды Git' },
        { order: 9, title: 'Задание: создать репозиторий и сделать PR', content: 'Задание: создай репозиторий на GitHub и сделай Pull Request' },
      ],
    },
    {
      title: 'Основы SQL',
      description: 'Научись писать SQL-запросы для работы с реляционными базами данных. SELECT, INSERT, JOIN и агрегация — с практикой на каждом уроке.',
      lessons: [
        { order: 1,  title: 'Что такое базы данных и SQL',             content: 'Видеоурок: Что такое базы данных и SQL' },
        { order: 2,  title: 'SELECT, WHERE, ORDER BY',                 content: 'Видеоурок: SELECT, WHERE, ORDER BY' },
        { order: 3,  title: 'INSERT, UPDATE, DELETE',                  content: 'Видеоурок: INSERT, UPDATE, DELETE' },
        { order: 4,  title: 'Квиз: базовые SQL запросы',               content: 'Проверь себя: базовые SQL запросы' },
        { order: 5,  title: 'Типы данных и создание таблиц',           content: 'Видеоурок: Типы данных и создание таблиц' },
        { order: 6,  title: 'JOIN: объединение таблиц',                content: 'Видеоурок: JOIN — объединение таблиц' },
        { order: 7,  title: 'Агрегатные функции: COUNT, SUM, AVG',     content: 'Видеоурок: Агрегатные функции — COUNT, SUM, AVG' },
        { order: 8,  title: 'GROUP BY и HAVING',                       content: 'Видеоурок: GROUP BY и HAVING' },
        { order: 9,  title: 'Читать: SQL документация',                content: 'Материал для чтения: SQL документация' },
        { order: 10, title: 'Задание: база данных интернет-магазина',   content: 'Задание: спроектируй и заполни базу данных интернет-магазина' },
      ],
    },
    {
      title: 'Введение в командную строку Linux',
      description: 'Основы работы с терминалом Linux/Unix. Навигация по файловой системе, управление файлами и базовые команды.',
      lessons: [
        { order: 1, title: 'Что такое командная строка и зачем она нужна', content: 'Видеоурок: Что такое командная строка и зачем она нужна' },
        { order: 2, title: 'Навигация: ls, cd, pwd, mkdir',               content: 'Видеоурок: Навигация — ls, cd, pwd, mkdir' },
        { order: 3, title: 'Работа с файлами: cp, mv, rm, cat',           content: 'Видеоурок: Работа с файлами — cp, mv, rm, cat' },
        { order: 4, title: 'Права доступа: chmod, chown',                 content: 'Видеоурок: Права доступа — chmod, chown' },
        { order: 5, title: 'Квиз: базовые команды Linux',                 content: 'Проверь себя: базовые команды Linux' },
        { order: 6, title: 'Переменные окружения и .bashrc',              content: 'Видеоурок: Переменные окружения и .bashrc' },
        { order: 7, title: 'Pipes и перенаправление вывода',              content: 'Видеоурок: Pipes и перенаправление вывода' },
        { order: 8, title: 'Задание: автоматизировать задачи через bash-скрипт', content: 'Задание: напиши bash-скрипт для автоматизации задач' },
      ],
    },
    {
      title: 'Основы TypeScript',
      description: 'TypeScript — это JavaScript с типами. Научись описывать типы, интерфейсы, дженерики и использовать TS в реальных проектах.',
      lessons: [
        { order: 1,  title: 'Зачем TypeScript и как его установить',             content: 'Видеоурок: Зачем TypeScript и как его установить' },
        { order: 2,  title: 'Базовые типы: string, number, boolean, array',      content: 'Видеоурок: Базовые типы — string, number, boolean, array' },
        { order: 3,  title: 'Interfaces и Type Aliases',                         content: 'Видеоурок: Interfaces и Type Aliases' },
        { order: 4,  title: 'Квиз: типизация в TypeScript',                      content: 'Проверь себя: типизация в TypeScript' },
        { order: 5,  title: 'Функции с типами и опциональные параметры',         content: 'Видеоурок: Функции с типами и опциональные параметры' },
        { order: 6,  title: 'Union и Intersection types',                        content: 'Видеоурок: Union и Intersection types' },
        { order: 7,  title: 'Enums и Tuple',                                     content: 'Видеоурок: Enums и Tuple в TypeScript' },
        { order: 8,  title: 'Классы и модификаторы доступа',                     content: 'Видеоурок: Классы и модификаторы доступа' },
        { order: 9,  title: 'Читать: официальная документация TS',               content: 'Материал для чтения: официальная документация TypeScript' },
        { order: 10, title: 'Задание: типизировать JS проект на TS',             content: 'Задание: конвертируй JS проект в TypeScript' },
      ],
    },
    {
      title: 'Как работает интернет и HTTP',
      description: 'Понять как устроен веб изнутри: DNS, HTTP/HTTPS, методы запросов, статус-коды, заголовки и REST.',
      lessons: [
        { order: 1, title: 'Как работает интернет: IP, DNS, TCP/IP',    content: 'Видеоурок: Как работает интернет — IP, DNS, TCP/IP' },
        { order: 2, title: 'HTTP запросы: GET, POST, PUT, DELETE',      content: 'Видеоурок: HTTP запросы — GET, POST, PUT, DELETE' },
        { order: 3, title: 'Статус-коды HTTP: 200, 404, 500 и другие', content: 'Видеоурок: Статус-коды HTTP' },
        { order: 4, title: 'Заголовки запросов и ответов',             content: 'Видеоурок: Заголовки HTTP запросов и ответов' },
        { order: 5, title: 'HTTPS и сертификаты SSL/TLS',              content: 'Видеоурок: HTTPS и сертификаты SSL/TLS' },
        { order: 6, title: 'Что такое REST API',                       content: 'Видеоурок: Что такое REST API' },
        { order: 7, title: 'Квиз: HTTP протокол',                      content: 'Проверь себя: HTTP протокол' },
        { order: 8, title: 'Задание: исследовать запросы в DevTools',  content: 'Задание: исследуй HTTP запросы через браузерные DevTools' },
      ],
    },
    {
      title: 'React.js — первое знакомство',
      description: 'Введение в React: компоненты, JSX, props и state. Создашь свои первые компоненты и поймёшь принципы реактивного UI.',
      lessons: [
        { order: 1,  title: 'Что такое React и зачем он нужен',               content: 'Видеоурок: Что такое React и зачем он нужен' },
        { order: 2,  title: 'Создание проекта: Vite + React',                 content: 'Видеоурок: Создание проекта с Vite + React' },
        { order: 3,  title: 'JSX: HTML внутри JavaScript',                   content: 'Видеоурок: JSX — HTML внутри JavaScript' },
        { order: 4,  title: 'Компоненты: функциональные компоненты',         content: 'Видеоурок: Функциональные компоненты React' },
        { order: 5,  title: 'Props: передача данных между компонентами',     content: 'Видеоурок: Props — передача данных между компонентами' },
        { order: 6,  title: 'Квиз: компоненты и props',                      content: 'Проверь себя: компоненты и props' },
        { order: 7,  title: 'useState: состояние компонента',                content: 'Видеоурок: useState — состояние компонента' },
        { order: 8,  title: 'Обработка событий: onClick, onChange',          content: 'Видеоурок: Обработка событий — onClick, onChange' },
        { order: 9,  title: 'Рендер списков и условный рендеринг',           content: 'Видеоурок: Рендер списков и условный рендеринг' },
        { order: 10, title: 'Задание: Todo-список на React',                 content: 'Задание: создай Todo-список на React' },
      ],
    },
    {
      title: 'Docker для разработчиков',
      description: 'Введение в контейнеризацию с Docker. Образы, контейнеры, Dockerfile и Docker Compose — с практическими примерами.',
      lessons: [
        { order: 1, title: 'Что такое Docker и зачем он нужен',              content: 'Видеоурок: Что такое Docker и зачем он нужен' },
        { order: 2, title: 'Образы и контейнеры: базовые понятия',          content: 'Видеоурок: Образы и контейнеры — базовые понятия' },
        { order: 3, title: 'Основные команды: run, ps, stop, rm',           content: 'Видеоурок: Основные команды Docker — run, ps, stop, rm' },
        { order: 4, title: 'Квиз: Docker основы',                          content: 'Проверь себя: Docker основы' },
        { order: 5, title: 'Dockerfile: создаём свой образ',                content: 'Видеоурок: Dockerfile — создаём свой образ' },
        { order: 6, title: 'Volumes и Networks в Docker',                  content: 'Видеоурок: Volumes и Networks в Docker' },
        { order: 7, title: 'Docker Compose: несколько сервисов',           content: 'Видеоурок: Docker Compose — несколько сервисов' },
        { order: 8, title: 'Читать: Docker документация',                  content: 'Материал для чтения: официальная документация Docker' },
        { order: 9, title: 'Задание: упаковать Node.js приложение в Docker', content: 'Задание: упакуй Node.js приложение в Docker-контейнер' },
      ],
    },
    {
      title: 'Алгоритмы: введение',
      description: 'Базовые алгоритмы и структуры данных для начинающих. Сложность алгоритмов (Big O), сортировки, поиск и рекурсия.',
      lessons: [
        { order: 1, title: 'Что такое алгоритм и зачем его изучать',           content: 'Видеоурок: Что такое алгоритм и зачем его изучать' },
        { order: 2, title: 'Big O нотация: O(n), O(log n), O(n²)',            content: 'Видеоурок: Big O нотация — O(n), O(log n), O(n²)' },
        { order: 3, title: 'Массивы и связные списки',                        content: 'Видеоурок: Массивы и связные списки' },
        { order: 4, title: 'Стек и очередь',                                  content: 'Видеоурок: Стек и очередь' },
        { order: 5, title: 'Квиз: сложность алгоритмов',                      content: 'Проверь себя: сложность алгоритмов' },
        { order: 6, title: 'Сортировка пузырьком и выбором',                  content: 'Видеоурок: Сортировка пузырьком и выбором' },
        { order: 7, title: 'Бинарный поиск',                                  content: 'Видеоурок: Бинарный поиск' },
        { order: 8, title: 'Введение в рекурсию',                             content: 'Видеоурок: Введение в рекурсию' },
        { order: 9, title: 'Задание: реализовать сортировку на Python/JS',    content: 'Задание: реализуй алгоритм сортировки на Python или JavaScript' },
      ],
    },
    {
      title: 'Node.js для начинающих',
      description: 'Основы разработки на Node.js: модули, работа с файлами, создание HTTP-сервера и знакомство с npm.',
      lessons: [
        { order: 1, title: 'Что такое Node.js и Event Loop',                      content: 'Видеоурок: Что такое Node.js и Event Loop' },
        { order: 2, title: 'Модули: require/import, встроенные модули',           content: 'Видеоурок: Модули — require/import, встроенные модули' },
        { order: 3, title: 'Работа с файловой системой (fs)',                     content: 'Видеоурок: Работа с файловой системой через модуль fs' },
        { order: 4, title: 'npm: установка и управление пакетами',               content: 'Видеоурок: npm — установка и управление пакетами' },
        { order: 5, title: 'Квиз: основы Node.js',                               content: 'Проверь себя: основы Node.js' },
        { order: 6, title: 'Создание HTTP сервера',                              content: 'Видеоурок: Создание HTTP сервера на Node.js' },
        { order: 7, title: 'Асинхронность: callbacks, Promises, async/await',    content: 'Видеоурок: Асинхронность — callbacks, Promises, async/await' },
        { order: 8, title: 'Express.js: первое веб-приложение',                  content: 'Видеоурок: Express.js — первое веб-приложение' },
        { order: 9, title: 'Задание: REST API на Express с 3 эндпоинтами',       content: 'Задание: создай REST API на Express с 3 эндпоинтами' },
      ],
    },
    {
      title: 'Основы UI/UX для разработчиков',
      description: 'Минимум дизайна для тех, кто пишет код: сетки, типографика, цвет, компоненты и Figma на практике.',
      lessons: [
        { order: 1, title: 'Разница между UI и UX',                            content: 'Видеоурок: Разница между UI и UX' },
        { order: 2, title: 'Основы типографики: шрифты, размеры, отступы',    content: 'Видеоурок: Основы типографики — шрифты, размеры, отступы' },
        { order: 3, title: 'Теория цвета для интерфейсов',                    content: 'Видеоурок: Теория цвета для интерфейсов' },
        { order: 4, title: 'Сетки и отступы (8px система)',                   content: 'Видеоурок: Сетки и отступы — 8px система' },
        { order: 5, title: 'Квиз: принципы UI дизайна',                       content: 'Проверь себя: принципы UI дизайна' },
        { order: 6, title: 'Figma: базовые инструменты',                      content: 'Видеоурок: Figma — базовые инструменты' },
        { order: 7, title: 'Компоненты и Auto Layout в Figma',                content: 'Видеоурок: Компоненты и Auto Layout в Figma' },
        { order: 8, title: 'Задание: спроектировать экран входа в Figma',     content: 'Задание: спроектируй экран авторизации в Figma' },
      ],
    },
    {
      title: 'PostgreSQL: основы работы',
      description: 'Практический курс по PostgreSQL: установка, создание таблиц, запросы, индексы и работа с psql и pgAdmin.',
      lessons: [
        { order: 1, title: 'Что такое PostgreSQL и его особенности',          content: 'Видеоурок: Что такое PostgreSQL и его особенности' },
        { order: 2, title: 'Установка PostgreSQL и pgAdmin',                  content: 'Видеоурок: Установка PostgreSQL и pgAdmin' },
        { order: 3, title: 'Создание БД, таблиц и типы данных',              content: 'Видеоурок: Создание БД, таблиц и типы данных' },
        { order: 4, title: 'CRUD запросы в PostgreSQL',                      content: 'Видеоурок: CRUD запросы в PostgreSQL' },
        { order: 5, title: 'Квиз: основы PostgreSQL',                        content: 'Проверь себя: основы PostgreSQL' },
        { order: 6, title: 'Ограничения: PRIMARY KEY, FOREIGN KEY, UNIQUE',  content: 'Видеоурок: Ограничения — PRIMARY KEY, FOREIGN KEY, UNIQUE' },
        { order: 7, title: 'Индексы: зачем нужны и как создать',             content: 'Видеоурок: Индексы — зачем нужны и как создать' },
        { order: 8, title: 'Работа с psql в командной строке',               content: 'Видеоурок: Работа с psql в командной строке' },
        { order: 9, title: 'Задание: создать схему БД для блога',            content: 'Задание: спроектируй схему базы данных для блог-платформы' },
      ],
    },
    {
      title: 'Основы кибербезопасности',
      description: 'Базовые понятия информационной безопасности: угрозы, атаки, пароли, шифрование и безопасная разработка.',
      lessons: [
        { order: 1, title: 'Введение в кибербезопасность',                           content: 'Видеоурок: Введение в кибербезопасность' },
        { order: 2, title: 'Типы атак: фишинг, SQL injection, XSS',                 content: 'Видеоурок: Типы атак — фишинг, SQL injection, XSS' },
        { order: 3, title: 'Пароли и аутентификация: хеширование, соль',            content: 'Видеоурок: Пароли и аутентификация — хеширование, соль' },
        { order: 4, title: 'Квиз: базовая безопасность',                            content: 'Проверь себя: базовая безопасность' },
        { order: 5, title: 'HTTPS, SSL/TLS и сертификаты',                          content: 'Видеоурок: HTTPS, SSL/TLS и сертификаты' },
        { order: 6, title: 'Основы шифрования: симметричное и асимметричное',       content: 'Видеоурок: Основы шифрования — симметричное и асимметричное' },
        { order: 7, title: 'Читать: OWASP Top 10 угроз',                            content: 'Материал для чтения: OWASP Top 10 угроз безопасности' },
        { order: 8, title: 'Задание: найти уязвимости в демо-сайте',                content: 'Задание: найди и опиши уязвимости в демонстрационном сайте' },
      ],
    },
    {
      title: 'React Native: мобильная разработка с нуля',
      description: 'Создай своё первое мобильное приложение с React Native. Компоненты, стилизация, навигация и работа с API.',
      lessons: [
        { order: 1,  title: 'Что такое React Native и как он работает',            content: 'Видеоурок: Что такое React Native и как он работает' },
        { order: 2,  title: 'Настройка окружения: Expo CLI',                       content: 'Видеоурок: Настройка окружения с Expo CLI' },
        { order: 3,  title: 'Основные компоненты: View, Text, Image, Button',      content: 'Видеоурок: Основные компоненты — View, Text, Image, Button' },
        { order: 4,  title: 'StyleSheet: стилизация в React Native',               content: 'Видеоурок: StyleSheet — стилизация в React Native' },
        { order: 5,  title: 'Квиз: основы React Native',                          content: 'Проверь себя: основы React Native' },
        { order: 6,  title: 'useState и обработка событий',                       content: 'Видеоурок: useState и обработка событий' },
        { order: 7,  title: 'FlatList и ScrollView: списки',                      content: 'Видеоурок: FlatList и ScrollView — работа со списками' },
        { order: 8,  title: 'React Navigation: переходы между экранами',          content: 'Видеоурок: React Navigation — переходы между экранами' },
        { order: 9,  title: 'Fetch API: загрузка данных с сервера',               content: 'Видеоурок: Fetch API — загрузка данных с сервера' },
        { order: 10, title: 'Задание: приложение погоды с API',                   content: 'Задание: создай приложение погоды с использованием открытого API' },
      ],
    },
    // ── Intermediate courses ─────────────────────────────────
    {
      title: 'React Advanced: хуки и паттерны',
      description: 'Углублённое изучение React: useEffect, useContext, useReducer, кастомные хуки и паттерны проектирования компонентов.',
      lessons: [
        { order: 1,  title: 'useEffect: побочные эффекты и зависимости',          content: 'Видеоурок: useEffect — побочные эффекты и зависимости' },
        { order: 2,  title: 'useContext: глобальное состояние без Redux',          content: 'Видеоурок: useContext — глобальное состояние без Redux' },
        { order: 3,  title: 'useReducer: сложная логика состояния',               content: 'Видеоурок: useReducer — сложная логика состояния' },
        { order: 4,  title: 'Кастомные хуки: создаём useLocalStorage',            content: 'Видеоурок: Кастомные хуки — создаём useLocalStorage' },
        { order: 5,  title: 'Квиз: React хуки',                                  content: 'Проверь себя: React хуки' },
        { order: 6,  title: 'useMemo и useCallback: оптимизация',                 content: 'Видеоурок: useMemo и useCallback — оптимизация' },
        { order: 7,  title: 'React.memo и предотвращение лишних рендеров',        content: 'Видеоурок: React.memo и предотвращение лишних рендеров' },
        { order: 8,  title: 'Compound Components паттерн',                        content: 'Видеоурок: Compound Components паттерн' },
        { order: 9,  title: 'Render Props и HOC паттерны',                        content: 'Видеоурок: Render Props и HOC паттерны' },
        { order: 10, title: 'Читать: React документация по хукам',                content: 'Материал для чтения: React документация по хукам' },
        { order: 11, title: 'Error Boundaries и Suspense',                        content: 'Видеоурок: Error Boundaries и Suspense' },
        { order: 12, title: 'Задание: дашборд с кастомными хуками',               content: 'Задание: создай дашборд с кастомными хуками' },
      ],
    },
    {
      title: 'NestJS: бэкенд на TypeScript',
      description: 'Создание REST API на NestJS: модули, контроллеры, сервисы, Pipes, Guards и работа с базой данных через Prisma.',
      lessons: [
        { order: 1,  title: 'Архитектура NestJS: модули, контроллеры, сервисы',   content: 'Видеоурок: Архитектура NestJS — модули, контроллеры, сервисы' },
        { order: 2,  title: 'Декораторы: @Controller, @Get, @Post и другие',      content: 'Видеоурок: Декораторы — @Controller, @Get, @Post и другие' },
        { order: 3,  title: 'DTOs и валидация через class-validator',             content: 'Видеоурок: DTOs и валидация через class-validator' },
        { order: 4,  title: 'Dependency Injection в NestJS',                      content: 'Видеоурок: Dependency Injection в NestJS' },
        { order: 5,  title: 'Квиз: архитектура NestJS',                          content: 'Проверь себя: архитектура NestJS' },
        { order: 6,  title: 'Pipes: трансформация и валидация данных',            content: 'Видеоурок: Pipes — трансформация и валидация данных' },
        { order: 7,  title: 'Guards: защита эндпоинтов',                          content: 'Видеоурок: Guards — защита эндпоинтов' },
        { order: 8,  title: 'Interceptors и Middleware',                          content: 'Видеоурок: Interceptors и Middleware' },
        { order: 9,  title: 'Подключение Prisma ORM к NestJS',                   content: 'Видеоурок: Подключение Prisma ORM к NestJS' },
        { order: 10, title: 'Exception Filters и обработка ошибок',              content: 'Видеоурок: Exception Filters и обработка ошибок' },
        { order: 11, title: 'Swagger: автодокументация API',                      content: 'Видеоурок: Swagger — автодокументация API' },
        { order: 12, title: 'Задание: REST API для блога с авторизацией',         content: 'Задание: создай REST API для блога с авторизацией' },
      ],
    },
    {
      title: 'PostgreSQL: продвинутые запросы',
      description: 'Оконные функции, CTE, оптимизация запросов через EXPLAIN ANALYZE, партиционирование и работа с JSON в PostgreSQL.',
      lessons: [
        { order: 1,  title: 'Подзапросы: correlated и uncorrelated',              content: 'Видеоурок: Подзапросы — correlated и uncorrelated' },
        { order: 2,  title: 'CTE (WITH): общие табличные выражения',              content: 'Видеоурок: CTE (WITH) — общие табличные выражения' },
        { order: 3,  title: 'Оконные функции: ROW_NUMBER, RANK, LAG, LEAD',       content: 'Видеоурок: Оконные функции — ROW_NUMBER, RANK, LAG, LEAD' },
        { order: 4,  title: 'Квиз: сложные SQL запросы',                         content: 'Проверь себя: сложные SQL запросы' },
        { order: 5,  title: 'EXPLAIN ANALYZE: анализ производительности',         content: 'Видеоурок: EXPLAIN ANALYZE — анализ производительности' },
        { order: 6,  title: 'Индексы: B-tree, Hash, GIN, GiST',                  content: 'Видеоурок: Индексы — B-tree, Hash, GIN, GiST' },
        { order: 7,  title: 'JSON и JSONB в PostgreSQL',                          content: 'Видеоурок: JSON и JSONB в PostgreSQL' },
        { order: 8,  title: 'Транзакции и уровни изоляции',                      content: 'Видеоурок: Транзакции и уровни изоляции' },
        { order: 9,  title: 'Читать: PostgreSQL документация по индексам',        content: 'Материал для чтения: PostgreSQL документация по индексам' },
        { order: 10, title: 'Задание: оптимизировать медленные запросы',          content: 'Задание: оптимизируй медленные запросы с помощью индексов и EXPLAIN' },
      ],
    },
    {
      title: 'Python: ООП и паттерны проектирования',
      description: 'Объектно-ориентированное программирование на Python: классы, наследование, полиморфизм и популярные паттерны (Factory, Singleton, Observer).',
      lessons: [
        { order: 1,  title: 'Классы и объекты: __init__, self, методы',           content: 'Видеоурок: Классы и объекты — __init__, self, методы' },
        { order: 2,  title: 'Наследование и super()',                             content: 'Видеоурок: Наследование и super()' },
        { order: 3,  title: 'Полиморфизм и абстрактные классы',                  content: 'Видеоурок: Полиморфизм и абстрактные классы' },
        { order: 4,  title: 'Dunder методы: __str__, __repr__, __len__',          content: 'Видеоурок: Dunder методы — __str__, __repr__, __len__' },
        { order: 5,  title: 'Квиз: ООП в Python',                               content: 'Проверь себя: ООП в Python' },
        { order: 6,  title: 'Паттерн Singleton и Factory',                       content: 'Видеоурок: Паттерн Singleton и Factory' },
        { order: 7,  title: 'Паттерн Observer и Strategy',                       content: 'Видеоурок: Паттерн Observer и Strategy' },
        { order: 8,  title: 'Декораторы функций и классов',                      content: 'Видеоурок: Декораторы функций и классов' },
        { order: 9,  title: 'Dataclasses и typing модуль',                       content: 'Видеоурок: Dataclasses и typing модуль' },
        { order: 10, title: 'Задание: система уведомлений через Observer',        content: 'Задание: реализуй систему уведомлений через паттерн Observer' },
      ],
    },
    {
      title: 'JWT аутентификация и авторизация',
      description: 'Реализация полноценной системы auth: JWT access/refresh токены, RBAC, хеширование паролей и защита маршрутов.',
      lessons: [
        { order: 1,  title: 'Как работает JWT: структура токена',                 content: 'Видеоурок: Как работает JWT — структура токена' },
        { order: 2,  title: 'Access и Refresh токены: зачем оба',                 content: 'Видеоурок: Access и Refresh токены — зачем оба' },
        { order: 3,  title: 'Хеширование паролей: bcrypt и argon2',               content: 'Видеоурок: Хеширование паролей — bcrypt и argon2' },
        { order: 4,  title: 'Реализация login/register на NestJS',                content: 'Видеоурок: Реализация login/register на NestJS' },
        { order: 5,  title: 'Квиз: JWT и аутентификация',                        content: 'Проверь себя: JWT и аутентификация' },
        { order: 6,  title: 'Guards и декоратор @CurrentUser',                    content: 'Видеоурок: Guards и декоратор @CurrentUser' },
        { order: 7,  title: 'RBAC: ролевая модель доступа',                      content: 'Видеоурок: RBAC — ролевая модель доступа' },
        { order: 8,  title: 'Хранение токенов: куки vs localStorage',            content: 'Видеоурок: Хранение токенов — куки vs localStorage' },
        { order: 9,  title: 'Читать: OWASP Authentication Cheatsheet',           content: 'Материал для чтения: OWASP Authentication Cheatsheet' },
        { order: 10, title: 'Задание: полная auth система с ролями',              content: 'Задание: реализуй полную систему аутентификации с ролями' },
      ],
    },
    {
      title: 'TypeScript: продвинутые типы',
      description: 'Дженерики, утилитарные типы, conditional types, mapped types и декораторы — TypeScript на профессиональном уровне.',
      lessons: [
        { order: 1,  title: 'Дженерики: T, K, V и ограничения (extends)',         content: 'Видеоурок: Дженерики — T, K, V и ограничения (extends)' },
        { order: 2,  title: 'Утилитарные типы: Partial, Required, Pick, Omit',    content: 'Видеоурок: Утилитарные типы — Partial, Required, Pick, Omit' },
        { order: 3,  title: 'Conditional Types: T extends U ? X : Y',            content: 'Видеоурок: Conditional Types — T extends U ? X : Y' },
        { order: 4,  title: 'Mapped Types и keyof, typeof',                      content: 'Видеоурок: Mapped Types и keyof, typeof' },
        { order: 5,  title: 'Квиз: продвинутые типы TypeScript',                 content: 'Проверь себя: продвинутые типы TypeScript' },
        { order: 6,  title: 'Template Literal Types',                            content: 'Видеоурок: Template Literal Types' },
        { order: 7,  title: 'Декораторы: class, method, property',               content: 'Видеоурок: Декораторы — class, method, property' },
        { order: 8,  title: 'Declaration merging и module augmentation',         content: 'Видеоурок: Declaration merging и module augmentation' },
        { order: 9,  title: 'Задание: типизировать сложный API клиент',          content: 'Задание: типизируй сложный API клиент с использованием дженериков' },
      ],
    },
    {
      title: 'Next.js 14: App Router и SSR',
      description: 'Изучи Next.js 14 с новым App Router: Server Components, SSR, SSG, ISR, Route Handlers и оптимизация производительности.',
      lessons: [
        { order: 1,  title: 'App Router vs Pages Router: что изменилось',         content: 'Видеоурок: App Router vs Pages Router — что изменилось' },
        { order: 2,  title: 'Server Components vs Client Components',             content: 'Видеоурок: Server Components vs Client Components' },
        { order: 3,  title: 'Layouts, Templates и Loading UI',                   content: 'Видеоурок: Layouts, Templates и Loading UI' },
        { order: 4,  title: 'SSR, SSG и ISR: когда что использовать',            content: 'Видеоурок: SSR, SSG и ISR — когда что использовать' },
        { order: 5,  title: 'Квиз: Next.js App Router',                         content: 'Проверь себя: Next.js App Router' },
        { order: 6,  title: 'Route Handlers: API маршруты в App Router',         content: 'Видеоурок: Route Handlers — API маршруты в App Router' },
        { order: 7,  title: 'Middleware: перехват запросов',                     content: 'Видеоурок: Middleware — перехват запросов' },
        { order: 8,  title: 'Оптимизация изображений и шрифтов',                content: 'Видеоурок: Оптимизация изображений и шрифтов в Next.js' },
        { order: 9,  title: 'Metadata API и SEO',                               content: 'Видеоурок: Metadata API и SEO в Next.js' },
        { order: 10, title: 'Читать: Next.js официальная документация',          content: 'Материал для чтения: Next.js официальная документация' },
        { order: 11, title: 'Задание: новостной сайт с SSR и ISR',               content: 'Задание: создай новостной сайт с SSR и ISR на Next.js 14' },
      ],
    },
    {
      title: 'Docker Compose и микросервисы',
      description: 'Оркестрация нескольких сервисов через Docker Compose: сети, volumes, переменные окружения и health checks.',
      lessons: [
        { order: 1,  title: 'Docker Compose: углублённый разбор yaml файла',      content: 'Видеоурок: Docker Compose — углублённый разбор yaml файла' },
        { order: 2,  title: 'Networks в Compose: bridge, host, overlay',          content: 'Видеоурок: Networks в Compose — bridge, host, overlay' },
        { order: 3,  title: 'Volumes: named, bind mounts, tmpfs',                content: 'Видеоурок: Volumes — named, bind mounts, tmpfs' },
        { order: 4,  title: 'Environment variables и .env файлы',                content: 'Видеоурок: Environment variables и .env файлы' },
        { order: 5,  title: 'Квиз: Docker Compose',                             content: 'Проверь себя: Docker Compose' },
        { order: 6,  title: 'Health checks и depends_on',                        content: 'Видеоурок: Health checks и depends_on' },
        { order: 7,  title: 'Многоэтапные сборки (multi-stage builds)',          content: 'Видеоурок: Многоэтапные сборки — multi-stage builds' },
        { order: 8,  title: 'Масштабирование сервисов: replicas',                content: 'Видеоурок: Масштабирование сервисов — replicas' },
        { order: 9,  title: 'Читать: Docker Compose документация',               content: 'Материал для чтения: Docker Compose документация' },
        { order: 10, title: 'Задание: развернуть fullstack приложение в Compose', content: 'Задание: разверни fullstack приложение с помощью Docker Compose' },
      ],
    },
    {
      title: 'Prisma ORM: работа с базой данных',
      description: 'Полное руководство по Prisma: схема, миграции, CRUD операции, relations, транзакции и оптимизация запросов.',
      lessons: [
        { order: 1,  title: 'Prisma schema: модели, типы, аннотации',            content: 'Видеоурок: Prisma schema — модели, типы, аннотации' },
        { order: 2,  title: 'Миграции: prisma migrate dev и deploy',             content: 'Видеоурок: Миграции — prisma migrate dev и deploy' },
        { order: 3,  title: 'Prisma Client: CRUD операции',                      content: 'Видеоурок: Prisma Client — CRUD операции' },
        { order: 4,  title: 'Relations: one-to-many, many-to-many',              content: 'Видеоурок: Relations — one-to-many, many-to-many' },
        { order: 5,  title: 'Квиз: Prisma ORM',                                 content: 'Проверь себя: Prisma ORM' },
        { order: 6,  title: 'Фильтрация, сортировка и пагинация',               content: 'Видеоурок: Фильтрация, сортировка и пагинация в Prisma' },
        { order: 7,  title: 'Транзакции: $transaction API',                     content: 'Видеоурок: Транзакции — $transaction API' },
        { order: 8,  title: 'Prisma Studio и seed файлы',                       content: 'Видеоурок: Prisma Studio и seed файлы' },
        { order: 9,  title: 'Задание: схема БД для социальной сети',            content: 'Задание: спроектируй схему БД для социальной сети в Prisma' },
      ],
    },
    {
      title: 'Git: ветвление и командная работа',
      description: 'Продвинутая работа с Git: rebase, cherry-pick, stash, hooks, стратегии ветвления (Gitflow, trunk-based) и разрешение конфликтов.',
      lessons: [
        { order: 1,  title: 'git rebase vs merge: когда что использовать',        content: 'Видеоурок: git rebase vs merge — когда что использовать' },
        { order: 2,  title: 'Interactive rebase: squash, fixup, reword',          content: 'Видеоурок: Interactive rebase — squash, fixup, reword' },
        { order: 3,  title: 'cherry-pick: перенос отдельных коммитов',            content: 'Видеоурок: cherry-pick — перенос отдельных коммитов' },
        { order: 4,  title: 'git stash: временное сохранение изменений',          content: 'Видеоурок: git stash — временное сохранение изменений' },
        { order: 5,  title: 'Квиз: продвинутый Git',                            content: 'Проверь себя: продвинутый Git' },
        { order: 6,  title: 'Git hooks: pre-commit, commit-msg',                 content: 'Видеоурок: Git hooks — pre-commit, commit-msg' },
        { order: 7,  title: 'Gitflow vs trunk-based development',                content: 'Видеоурок: Gitflow vs trunk-based development' },
        { order: 8,  title: 'Разрешение сложных конфликтов',                    content: 'Видеоурок: Разрешение сложных конфликтов в Git' },
        { order: 9,  title: 'Задание: настроить Gitflow для командного проекта', content: 'Задание: настрой Gitflow для командного проекта' },
      ],
    },
    {
      title: 'REST API: проектирование и лучшие практики',
      description: 'Как проектировать качественные REST API: именование, версионирование, пагинация, обработка ошибок и документация через Swagger.',
      lessons: [
        { order: 1,  title: 'Принципы REST: ресурсы, глаголы, stateless',        content: 'Видеоурок: Принципы REST — ресурсы, глаголы, stateless' },
        { order: 2,  title: 'Именование эндпоинтов: best practices',             content: 'Видеоурок: Именование эндпоинтов — best practices' },
        { order: 3,  title: 'HTTP статус коды: правильное использование',        content: 'Видеоурок: HTTP статус коды — правильное использование' },
        { order: 4,  title: 'Версионирование API: /v1, /v2',                    content: 'Видеоурок: Версионирование API — /v1, /v2' },
        { order: 5,  title: 'Квиз: REST API проектирование',                    content: 'Проверь себя: REST API проектирование' },
        { order: 6,  title: 'Пагинация: offset vs cursor based',                content: 'Видеоурок: Пагинация — offset vs cursor based' },
        { order: 7,  title: 'Обработка ошибок: единый формат ответа',           content: 'Видеоурок: Обработка ошибок — единый формат ответа' },
        { order: 8,  title: 'Swagger/OpenAPI: документирование API',            content: 'Видеоурок: Swagger/OpenAPI — документирование API' },
        { order: 9,  title: 'Читать: REST API Design Guidelines',               content: 'Материал для чтения: REST API Design Guidelines' },
        { order: 10, title: 'Задание: спроектировать API для маркетплейса',      content: 'Задание: спроектируй API для маркетплейса' },
      ],
    },
    {
      title: 'Python: работа с данными (pandas, numpy)',
      description: 'Обработка и анализ данных на Python с библиотеками pandas и numpy: загрузка, очистка, трансформация и визуализация данных.',
      lessons: [
        { order: 1,  title: 'NumPy: массивы, операции, broadcasting',            content: 'Видеоурок: NumPy — массивы, операции, broadcasting' },
        { order: 2,  title: 'Pandas: DataFrame и Series',                        content: 'Видеоурок: Pandas — DataFrame и Series' },
        { order: 3,  title: 'Загрузка данных: CSV, JSON, Excel',                content: 'Видеоурок: Загрузка данных — CSV, JSON, Excel' },
        { order: 4,  title: 'Очистка данных: NaN, дубликаты, типы',             content: 'Видеоурок: Очистка данных — NaN, дубликаты, типы' },
        { order: 5,  title: 'Квиз: pandas основы',                             content: 'Проверь себя: pandas основы' },
        { order: 6,  title: 'Группировка: groupby и агрегация',                 content: 'Видеоурок: Группировка — groupby и агрегация' },
        { order: 7,  title: 'Merge и Join таблиц в pandas',                     content: 'Видеоурок: Merge и Join таблиц в pandas' },
        { order: 8,  title: 'Визуализация: matplotlib и seaborn',               content: 'Видеоурок: Визуализация — matplotlib и seaborn' },
        { order: 9,  title: 'Читать: pandas документация',                      content: 'Материал для чтения: pandas документация' },
        { order: 10, title: 'Задание: анализ датасета продаж',                  content: 'Задание: проанализируй датасет продаж с помощью pandas' },
      ],
    },
    {
      title: 'WebSocket и реалтайм приложения',
      description: 'Создание реалтайм функциональности с Socket.io и NestJS: события, комнаты, broadcast и интеграция с фронтендом на React.',
      lessons: [
        { order: 1,  title: 'WebSocket vs HTTP: в чём разница',                  content: 'Видеоурок: WebSocket vs HTTP — в чём разница' },
        { order: 2,  title: 'Socket.io: установка и базовые события',            content: 'Видеоурок: Socket.io — установка и базовые события' },
        { order: 3,  title: 'Emit и on: отправка и получение событий',           content: 'Видеоурок: Emit и on — отправка и получение событий' },
        { order: 4,  title: 'Комнаты (rooms) и namespace',                      content: 'Видеоурок: Комнаты (rooms) и namespace в Socket.io' },
        { order: 5,  title: 'Квиз: Socket.io основы',                          content: 'Проверь себя: Socket.io основы' },
        { order: 6,  title: 'NestJS Gateway: @WebSocketGateway',                content: 'Видеоурок: NestJS Gateway — @WebSocketGateway' },
        { order: 7,  title: 'Аутентификация WebSocket соединений',              content: 'Видеоурок: Аутентификация WebSocket соединений' },
        { order: 8,  title: 'Интеграция Socket.io с React хуками',             content: 'Видеоурок: Интеграция Socket.io с React хуками' },
        { order: 9,  title: 'Задание: чат-приложение с комнатами',              content: 'Задание: создай чат-приложение с комнатами на Socket.io и NestJS' },
      ],
    },
    {
      title: 'CSS: Tailwind CSS и современная вёрстка',
      description: 'Utility-first подход с Tailwind CSS: конфигурация, responsive дизайн, dark mode, кастомные компоненты и оптимизация.',
      lessons: [
        { order: 1,  title: 'Философия utility-first: зачем Tailwind',           content: 'Видеоурок: Философия utility-first — зачем Tailwind' },
        { order: 2,  title: 'Установка и настройка tailwind.config.js',          content: 'Видеоурок: Установка и настройка tailwind.config.js' },
        { order: 3,  title: 'Основные классы: spacing, colors, typography',      content: 'Видеоурок: Основные классы — spacing, colors, typography' },
        { order: 4,  title: 'Flexbox и Grid через Tailwind',                    content: 'Видеоурок: Flexbox и Grid через Tailwind' },
        { order: 5,  title: 'Квиз: Tailwind CSS классы',                       content: 'Проверь себя: Tailwind CSS классы' },
        { order: 6,  title: 'Responsive дизайн: sm, md, lg, xl',               content: 'Видеоурок: Responsive дизайн — sm, md, lg, xl' },
        { order: 7,  title: 'Dark mode: class и media стратегии',               content: 'Видеоурок: Dark mode — class и media стратегии' },
        { order: 8,  title: 'Кастомизация: extend в конфиге',                  content: 'Видеоурок: Кастомизация — extend в конфиге Tailwind' },
        { order: 9,  title: 'Задание: лендинг с тёмной темой на Tailwind',      content: 'Задание: создай лендинг с тёмной темой на Tailwind CSS' },
      ],
    },
    {
      title: 'Алгоритмы: рекурсия и динамическое программирование',
      description: 'Углублённые алгоритмы: деревья, графы, рекурсия, мемоизация и классические задачи динамического программирования.',
      lessons: [
        { order: 1,  title: 'Рекурсия: базовый случай и стек вызовов',           content: 'Видеоурок: Рекурсия — базовый случай и стек вызовов' },
        { order: 2,  title: 'Деревья: бинарное дерево, обходы',                 content: 'Видеоурок: Деревья — бинарное дерево, обходы' },
        { order: 3,  title: 'Бинарное дерево поиска (BST)',                     content: 'Видеоурок: Бинарное дерево поиска (BST)' },
        { order: 4,  title: 'Графы: BFS и DFS',                                content: 'Видеоурок: Графы — BFS и DFS' },
        { order: 5,  title: 'Квиз: деревья и графы',                           content: 'Проверь себя: деревья и графы' },
        { order: 6,  title: 'Мемоизация: оптимизация рекурсии',                content: 'Видеоурок: Мемоизация — оптимизация рекурсии' },
        { order: 7,  title: 'Динамическое программирование: top-down',          content: 'Видеоурок: Динамическое программирование — top-down подход' },
        { order: 8,  title: 'ДП задачи: Fibonacci, Knapsack, Longest Common Subsequence', content: 'Видеоурок: ДП задачи — Fibonacci, Knapsack, Longest Common Subsequence' },
        { order: 9,  title: 'Читать: разбор задач LeetCode',                   content: 'Материал для чтения: разбор задач LeetCode' },
        { order: 10, title: 'Задание: решить 5 задач на ДП',                   content: 'Задание: решить 5 задач на динамическое программирование' },
      ],
    },
    {
      title: 'React Native: навигация и работа с API',
      description: 'Продвинутая разработка на React Native: стек навигации, Tab и Drawer навигация, работа с REST API, AsyncStorage и состояние через Zustand.',
      lessons: [
        { order: 1,  title: 'React Navigation v6: Stack Navigator',              content: 'Видеоурок: React Navigation v6 — Stack Navigator' },
        { order: 2,  title: 'Tab Navigator и Drawer Navigator',                 content: 'Видеоурок: Tab Navigator и Drawer Navigator' },
        { order: 3,  title: 'Передача параметров между экранами',               content: 'Видеоурок: Передача параметров между экранами' },
        { order: 4,  title: 'Axios в React Native: GET, POST запросы',          content: 'Видеоурок: Axios в React Native — GET, POST запросы' },
        { order: 5,  title: 'Квиз: навигация в React Native',                  content: 'Проверь себя: навигация в React Native' },
        { order: 6,  title: 'AsyncStorage: локальное хранилище',               content: 'Видеоурок: AsyncStorage — локальное хранилище' },
        { order: 7,  title: 'Zustand: глобальное состояние',                   content: 'Видеоурок: Zustand — глобальное состояние в React Native' },
        { order: 8,  title: 'Работа с формами: React Hook Form',               content: 'Видеоурок: Работа с формами — React Hook Form' },
        { order: 9,  title: 'Кастомные компоненты и переиспользование',         content: 'Видеоурок: Кастомные компоненты и переиспользование' },
        { order: 10, title: 'Задание: приложение новостей с авторизацией',      content: 'Задание: создай приложение новостей с авторизацией на React Native' },
      ],
    },
    // ── Advanced courses ─────────────────────────────────────
    {
      title: 'NestJS: микросервисная архитектура',
      description: 'Построение микросервисной системы на NestJS: транспорты (TCP, Redis, RabbitMQ), паттерны CQRS, Event Sourcing и межсервисное взаимодействие.',
      lessons: [
        { order: 1,  title: 'Монолит vs микросервисы: когда и зачем',            content: 'Видеоурок: Монолит vs микросервисы — когда и зачем' },
        { order: 2,  title: 'NestJS Microservices: транспортный слой',            content: 'Видеоурок: NestJS Microservices — транспортный слой' },
        { order: 3,  title: 'TCP транспорт: настройка клиента и сервера',         content: 'Видеоурок: TCP транспорт — настройка клиента и сервера' },
        { order: 4,  title: 'Redis транспорт: pub/sub паттерн',                  content: 'Видеоурок: Redis транспорт — pub/sub паттерн' },
        { order: 5,  title: 'RabbitMQ: очереди сообщений',                      content: 'Видеоурок: RabbitMQ — очереди сообщений' },
        { order: 6,  title: 'Квиз: микросервисная архитектура',                 content: 'Проверь себя: микросервисная архитектура' },
        { order: 7,  title: 'CQRS паттерн: команды и запросы',                  content: 'Видеоурок: CQRS паттерн — команды и запросы' },
        { order: 8,  title: 'Event Sourcing: история событий',                   content: 'Видеоурок: Event Sourcing — история событий' },
        { order: 9,  title: 'API Gateway: единая точка входа',                   content: 'Видеоурок: API Gateway — единая точка входа' },
        { order: 10, title: 'Distributed tracing: OpenTelemetry',               content: 'Видеоурок: Distributed tracing — OpenTelemetry' },
        { order: 11, title: 'Circuit Breaker и Retry паттерны',                 content: 'Видеоурок: Circuit Breaker и Retry паттерны' },
        { order: 12, title: 'Читать: Microservices patterns (Fowler)',           content: 'Материал для чтения: Microservices patterns (Fowler)' },
        { order: 13, title: 'Задание: система заказов из 3 микросервисов',       content: 'Задание: создай систему заказов из 3 микросервисов на NestJS' },
      ],
    },
    {
      title: 'PostgreSQL: высокая нагрузка и оптимизация',
      description: 'PostgreSQL под высокой нагрузкой: репликация, шардирование, connection pooling через PgBouncer, партиционирование таблиц и мониторинг.',
      lessons: [
        { order: 1,  title: 'Архитектура PostgreSQL изнутри',                   content: 'Видеоурок: Архитектура PostgreSQL изнутри' },
        { order: 2,  title: 'MVCC: как PostgreSQL управляет транзакциями',       content: 'Видеоурок: MVCC — как PostgreSQL управляет транзакциями' },
        { order: 3,  title: 'Партиционирование: range, list, hash',              content: 'Видеоурок: Партиционирование — range, list, hash' },
        { order: 4,  title: 'Репликация: primary-replica setup',                content: 'Видеоурок: Репликация — primary-replica setup' },
        { order: 5,  title: 'Квиз: PostgreSQL архитектура',                    content: 'Проверь себя: PostgreSQL архитектура' },
        { order: 6,  title: 'PgBouncer: connection pooling',                    content: 'Видеоурок: PgBouncer — connection pooling' },
        { order: 7,  title: 'Vacuum и autovacuum: борьба с bloat',              content: 'Видеоурок: Vacuum и autovacuum — борьба с bloat' },
        { order: 8,  title: 'Полнотекстовый поиск: tsvector и tsquery',         content: 'Видеоурок: Полнотекстовый поиск — tsvector и tsquery' },
        { order: 9,  title: 'pg_stat_statements: мониторинг запросов',          content: 'Видеоурок: pg_stat_statements — мониторинг запросов' },
        { order: 10, title: 'Шардирование с Citus',                             content: 'Видеоурок: Шардирование с Citus' },
        { order: 11, title: 'Читать: PostgreSQL Internals документация',        content: 'Материал для чтения: PostgreSQL Internals документация' },
        { order: 12, title: 'Задание: оптимизировать БД на 10M записей',        content: 'Задание: оптимизируй БД на 10M записей с помощью репликации и индексов' },
      ],
    },
    {
      title: 'Kubernetes: оркестрация контейнеров',
      description: 'Kubernetes с нуля до продакшена: Pods, Deployments, Services, Ingress, ConfigMaps, Secrets, Helm charts и мониторинг через Prometheus.',
      lessons: [
        { order: 1,  title: 'Архитектура Kubernetes: control plane и nodes',    content: 'Видеоурок: Архитектура Kubernetes — control plane и nodes' },
        { order: 2,  title: 'Pods: создание, жизненный цикл, проблемы',         content: 'Видеоурок: Pods — создание, жизненный цикл, проблемы' },
        { order: 3,  title: 'Deployments и ReplicaSets',                        content: 'Видеоурок: Deployments и ReplicaSets' },
        { order: 4,  title: 'Services: ClusterIP, NodePort, LoadBalancer',      content: 'Видеоурок: Services — ClusterIP, NodePort, LoadBalancer' },
        { order: 5,  title: 'Квиз: основные объекты Kubernetes',               content: 'Проверь себя: основные объекты Kubernetes' },
        { order: 6,  title: 'ConfigMaps и Secrets',                             content: 'Видеоурок: ConfigMaps и Secrets' },
        { order: 7,  title: 'Persistent Volumes и Storage Classes',             content: 'Видеоурок: Persistent Volumes и Storage Classes' },
        { order: 8,  title: 'Ingress: маршрутизация трафика',                  content: 'Видеоурок: Ingress — маршрутизация трафика' },
        { order: 9,  title: 'Helm: менеджер пакетов для K8s',                  content: 'Видеоурок: Helm — менеджер пакетов для K8s' },
        { order: 10, title: 'HPA: автомасштабирование подов',                  content: 'Видеоурок: HPA — автомасштабирование подов' },
        { order: 11, title: 'Prometheus + Grafana: мониторинг кластера',        content: 'Видеоурок: Prometheus + Grafana — мониторинг кластера' },
        { order: 12, title: 'Читать: Kubernetes документация',                  content: 'Материал для чтения: Kubernetes документация' },
        { order: 13, title: 'Задание: задеплоить fullstack приложение в K8s',   content: 'Задание: задеплои fullstack приложение в Kubernetes' },
      ],
    },
    {
      title: 'CI/CD: автоматизация деплоя',
      description: 'Построение полного CI/CD pipeline: GitHub Actions, автотесты, Docker build, деплой на сервер и управление секретами.',
      lessons: [
        { order: 1,  title: 'CI/CD концепция: от коммита до продакшена',        content: 'Видеоурок: CI/CD концепция — от коммита до продакшена' },
        { order: 2,  title: 'GitHub Actions: workflow, jobs, steps',            content: 'Видеоурок: GitHub Actions — workflow, jobs, steps' },
        { order: 3,  title: 'Автозапуск тестов на каждый PR',                  content: 'Видеоурок: Автозапуск тестов на каждый PR' },
        { order: 4,  title: 'Docker build и push в GitHub Container Registry',  content: 'Видеоурок: Docker build и push в GitHub Container Registry' },
        { order: 5,  title: 'Квиз: CI/CD пайплайны',                          content: 'Проверь себя: CI/CD пайплайны' },
        { order: 6,  title: 'Secrets и Environment variables в Actions',        content: 'Видеоурок: Secrets и Environment variables в GitHub Actions' },
        { order: 7,  title: 'Self-hosted runners: деплой на свой сервер',       content: 'Видеоурок: Self-hosted runners — деплой на свой сервер' },
        { order: 8,  title: 'Rolling updates и zero-downtime деплой',           content: 'Видеоурок: Rolling updates и zero-downtime деплой' },
        { order: 9,  title: 'Читать: GitHub Actions документация',              content: 'Материал для чтения: GitHub Actions документация' },
        { order: 10, title: 'Задание: полный CI/CD для NestJS + Next.js',       content: 'Задание: настрой полный CI/CD пайплайн для NestJS + Next.js' },
      ],
    },
    {
      title: 'React: производительность и архитектура',
      description: 'Оптимизация React приложений: профилирование, виртуализация списков, code splitting, lazy loading, state management архитектура и тестирование.',
      lessons: [
        { order: 1,  title: 'React Profiler: поиск узких мест',                 content: 'Видеоурок: React Profiler — поиск узких мест' },
        { order: 2,  title: 'Виртуализация: react-window и react-virtual',      content: 'Видеоурок: Виртуализация — react-window и react-virtual' },
        { order: 3,  title: 'Code splitting: React.lazy и Suspense',            content: 'Видеоурок: Code splitting — React.lazy и Suspense' },
        { order: 4,  title: 'Zustand vs Redux Toolkit: выбор стейт менеджера',  content: 'Видеоурок: Zustand vs Redux Toolkit — выбор стейт менеджера' },
        { order: 5,  title: 'Квиз: оптимизация React',                        content: 'Проверь себя: оптимизация React' },
        { order: 6,  title: 'React Query: серверное состояние',                content: 'Видеоурок: React Query — серверное состояние' },
        { order: 7,  title: 'Concurrent Features: useTransition, useDeferredValue', content: 'Видеоурок: Concurrent Features — useTransition и useDeferredValue' },
        { order: 8,  title: 'Тестирование: React Testing Library',             content: 'Видеоурок: Тестирование — React Testing Library' },
        { order: 9,  title: 'Feature-Sliced Design архитектура',               content: 'Видеоурок: Feature-Sliced Design архитектура' },
        { order: 10, title: 'Задание: оптимизировать приложение с 10k элементов', content: 'Задание: оптимизируй React приложение с 10k элементов списка' },
      ],
    },
    {
      title: 'TypeScript: компиляторный API и метапрограммирование',
      description: 'Глубокое погружение в TypeScript: собственные трансформеры, работа с Compiler API, advanced типы, type-level программирование.',
      lessons: [
        { order: 1,  title: 'TypeScript Compiler API: AST и трансформации',     content: 'Видеоурок: TypeScript Compiler API — AST и трансформации' },
        { order: 2,  title: 'Infer keyword: выведение типов внутри conditional', content: 'Видеоурок: Infer keyword — выведение типов внутри conditional' },
        { order: 3,  title: 'Recursive Types: бесконечно вложенные структуры',  content: 'Видеоурок: Recursive Types — бесконечно вложенные структуры' },
        { order: 4,  title: 'Variance: covariance и contravariance',            content: 'Видеоурок: Variance — covariance и contravariance' },
        { order: 5,  title: 'Квиз: type-level TypeScript',                     content: 'Проверь себя: type-level TypeScript' },
        { order: 6,  title: 'Собственный ESLint плагин на TS',                 content: 'Видеоурок: Собственный ESLint плагин на TypeScript' },
        { order: 7,  title: 'Брендирование типов (branded types)',              content: 'Видеоурок: Брендирование типов (branded types)' },
        { order: 8,  title: 'Phantom Types и type-safe builder паттерн',        content: 'Видеоурок: Phantom Types и type-safe builder паттерн' },
        { order: 9,  title: 'Читать: TypeScript Deep Dive (Basarat)',           content: 'Материал для чтения: TypeScript Deep Dive (Basarat)' },
        { order: 10, title: 'Задание: написать кодогенератор типов из JSON схемы', content: 'Задание: напиши кодогенератор TypeScript типов из JSON схемы' },
      ],
    },
    {
      title: 'Безопасность веб-приложений: атаки и защита',
      description: 'Продвинутая веб-безопасность: OWASP Top 10 глубоко, SQL injection, XSS, CSRF, SSRF, Rate Limiting, пентестинг и secure code review.',
      lessons: [
        { order: 1,  title: 'OWASP Top 10 2023: разбор каждой уязвимости',      content: 'Видеоурок: OWASP Top 10 2023 — разбор каждой уязвимости' },
        { order: 2,  title: 'SQL Injection: от простого до blind и time-based',  content: 'Видеоурок: SQL Injection — от простого до blind и time-based' },
        { order: 3,  title: 'XSS: stored, reflected, DOM-based',                content: 'Видеоурок: XSS — stored, reflected, DOM-based' },
        { order: 4,  title: 'CSRF: атака и защита через токены',                content: 'Видеоурок: CSRF — атака и защита через токены' },
        { order: 5,  title: 'Квиз: уязвимости веб-приложений',                 content: 'Проверь себя: уязвимости веб-приложений' },
        { order: 6,  title: 'SSRF: Server-Side Request Forgery',                content: 'Видеоурок: SSRF — Server-Side Request Forgery' },
        { order: 7,  title: 'JWT атаки: alg:none, key confusion',               content: 'Видеоурок: JWT атаки — alg:none и key confusion' },
        { order: 8,  title: 'Rate Limiting и защита от brute force',            content: 'Видеоурок: Rate Limiting и защита от brute force' },
        { order: 9,  title: 'Secure code review: чеклист и инструменты',        content: 'Видеоурок: Secure code review — чеклист и инструменты' },
        { order: 10, title: 'Пентестинг с Burp Suite',                          content: 'Видеоурок: Пентестинг с Burp Suite' },
        { order: 11, title: 'Читать: OWASP Testing Guide',                      content: 'Материал для чтения: OWASP Testing Guide' },
        { order: 12, title: 'Задание: найти и закрыть 5 уязвимостей в демо-API', content: 'Задание: найди и закрой 5 уязвимостей в демонстрационном API' },
      ],
    },
    {
      title: 'Python: асинхронность и высокая производительность',
      description: 'asyncio, aiohttp, FastAPI под нагрузкой, Celery для фоновых задач, профилирование Python кода и оптимизация с помощью Cython и multiprocessing.',
      lessons: [
        { order: 1,  title: 'asyncio изнутри: event loop, coroutines, tasks',   content: 'Видеоурок: asyncio изнутри — event loop, coroutines, tasks' },
        { order: 2,  title: 'async/await: правильные паттерны',                 content: 'Видеоурок: async/await — правильные паттерны' },
        { order: 3,  title: 'aiohttp: асинхронные HTTP запросы',                content: 'Видеоурок: aiohttp — асинхронные HTTP запросы' },
        { order: 4,  title: 'FastAPI: асинхронный REST API',                    content: 'Видеоурок: FastAPI — асинхронный REST API' },
        { order: 5,  title: 'Квиз: asyncio и асинхронность',                   content: 'Проверь себя: asyncio и асинхронность' },
        { order: 6,  title: 'Celery: фоновые задачи и очереди',                content: 'Видеоурок: Celery — фоновые задачи и очереди' },
        { order: 7,  title: 'multiprocessing vs multithreading vs asyncio',     content: 'Видеоурок: multiprocessing vs multithreading vs asyncio' },
        { order: 8,  title: 'Профилирование: cProfile, py-spy, memory_profiler', content: 'Видеоурок: Профилирование — cProfile, py-spy, memory_profiler' },
        { order: 9,  title: 'Оптимизация: Cython и C extensions',              content: 'Видеоурок: Оптимизация — Cython и C extensions' },
        { order: 10, title: 'Задание: высоконагруженный парсер 1M страниц',     content: 'Задание: напиши высоконагруженный асинхронный парсер 1M страниц' },
      ],
    },
    {
      title: 'Алгоритмы: продвинутые структуры данных',
      description: 'Продвинутые алгоритмы и структуры данных: красно-чёрные деревья, B-деревья, алгоритмы на графах, потоки в сети и строковые алгоритмы.',
      lessons: [
        { order: 1,  title: 'Красно-чёрные деревья: балансировка',              content: 'Видеоурок: Красно-чёрные деревья — балансировка' },
        { order: 2,  title: 'B-деревья и B+-деревья: как устроены индексы БД',  content: 'Видеоурок: B-деревья и B+-деревья — как устроены индексы БД' },
        { order: 3,  title: 'Heap и Priority Queue: применения',                content: 'Видеоурок: Heap и Priority Queue — применения' },
        { order: 4,  title: 'Алгоритм Дейкстры и A*',                          content: 'Видеоурок: Алгоритм Дейкстры и A*' },
        { order: 5,  title: 'Квиз: продвинутые структуры данных',              content: 'Проверь себя: продвинутые структуры данных' },
        { order: 6,  title: 'Алгоритм Флойда-Уоршелла: кратчайшие пути',      content: 'Видеоурок: Алгоритм Флойда-Уоршелла — кратчайшие пути' },
        { order: 7,  title: 'Потоки в сети: алгоритм Форда-Фалкерсона',        content: 'Видеоурок: Потоки в сети — алгоритм Форда-Фалкерсона' },
        { order: 8,  title: 'Строковые алгоритмы: KMP, Rabin-Karp',            content: 'Видеоурок: Строковые алгоритмы — KMP, Rabin-Karp' },
        { order: 9,  title: 'Segment Tree и Fenwick Tree',                      content: 'Видеоурок: Segment Tree и Fenwick Tree' },
        { order: 10, title: 'Читать: CLRS Introduction to Algorithms',          content: 'Материал для чтения: CLRS Introduction to Algorithms' },
        { order: 11, title: 'Задание: решить 5 hard задач на LeetCode',         content: 'Задание: реши 5 hard задач на LeetCode' },
      ],
    },
    {
      title: 'Проектирование системы (System Design)',
      description: 'Как проектировать масштабируемые системы: балансировщики нагрузки, кэширование, CDN, базы данных, очереди и разбор реальных систем (Twitter, YouTube, Uber).',
      lessons: [
        { order: 1,  title: 'Масштабирование: вертикальное vs горизонтальное',  content: 'Видеоурок: Масштабирование — вертикальное vs горизонтальное' },
        { order: 2,  title: 'Load Balancer: алгоритмы и реализации',            content: 'Видеоурок: Load Balancer — алгоритмы и реализации' },
        { order: 3,  title: 'Кэширование: Redis, стратегии и инвалидация',      content: 'Видеоурок: Кэширование — Redis, стратегии и инвалидация' },
        { order: 4,  title: 'CDN: как работает и когда нужен',                 content: 'Видеоурок: CDN — как работает и когда нужен' },
        { order: 5,  title: 'Квиз: компоненты системного дизайна',             content: 'Проверь себя: компоненты системного дизайна' },
        { order: 6,  title: 'CAP теорема: consistency, availability, partition', content: 'Видеоурок: CAP теорема — consistency, availability, partition' },
        { order: 7,  title: 'Очереди сообщений: Kafka vs RabbitMQ',            content: 'Видеоурок: Очереди сообщений — Kafka vs RabbitMQ' },
        { order: 8,  title: 'Разбор Twitter: хранение твитов и лента',         content: 'Видеоурок: Разбор Twitter — хранение твитов и лента' },
        { order: 9,  title: 'Разбор YouTube: загрузка и стриминг видео',        content: 'Видеоурок: Разбор YouTube — загрузка и стриминг видео' },
        { order: 10, title: 'Разбор Uber: геолокация в реалтайм',              content: 'Видеоурок: Разбор Uber — геолокация в реалтайм' },
        { order: 11, title: 'Читать: Designing Data-Intensive Applications',    content: 'Материал для чтения: Designing Data-Intensive Applications' },
        { order: 12, title: 'Задание: спроектировать систему для 10M пользователей', content: 'Задание: спроектируй систему для 10M пользователей' },
      ],
    },
    {
      title: 'Redis: кэширование и структуры данных',
      description: 'Redis в продакшене: типы данных, Pub/Sub, Streams, кэш-стратегии, Redis Cluster, Sentinel и интеграция с NestJS.',
      lessons: [
        { order: 1,  title: 'Redis архитектура: in-memory, persistence',        content: 'Видеоурок: Redis архитектура — in-memory, persistence' },
        { order: 2,  title: 'Типы данных: String, Hash, List, Set, ZSet',       content: 'Видеоурок: Типы данных — String, Hash, List, Set, ZSet' },
        { order: 3,  title: 'TTL и стратегии вытеснения (eviction)',            content: 'Видеоурок: TTL и стратегии вытеснения (eviction)' },
        { order: 4,  title: 'Кэш-паттерны: Cache-Aside, Write-Through, Write-Back', content: 'Видеоурок: Кэш-паттерны — Cache-Aside, Write-Through, Write-Back' },
        { order: 5,  title: 'Квиз: Redis структуры данных',                    content: 'Проверь себя: Redis структуры данных' },
        { order: 6,  title: 'Pub/Sub: события и подписки',                     content: 'Видеоурок: Pub/Sub — события и подписки' },
        { order: 7,  title: 'Redis Streams: очереди сообщений',                content: 'Видеоурок: Redis Streams — очереди сообщений' },
        { order: 8,  title: 'Redis Cluster и Sentinel: отказоустойчивость',    content: 'Видеоурок: Redis Cluster и Sentinel — отказоустойчивость' },
        { order: 9,  title: 'Интеграция Redis с NestJS через ioredis',          content: 'Видеоурок: Интеграция Redis с NestJS через ioredis' },
        { order: 10, title: 'Задание: кэш-слой для API с инвалидацией',         content: 'Задание: реализуй кэш-слой для API с инвалидацией кэша' },
      ],
    },
    {
      title: 'Next.js: продакшен архитектура',
      description: 'Next.js на продакшене: монорепо с Turborepo, edge функции, Middleware, ISR с on-demand revalidation, мониторинг и оптимизация Core Web Vitals.',
      lessons: [
        { order: 1,  title: 'Монорепо с Turborepo: структура и кэширование',    content: 'Видеоурок: Монорепо с Turborepo — структура и кэширование' },
        { order: 2,  title: 'Edge Runtime: возможности и ограничения',          content: 'Видеоурок: Edge Runtime — возможности и ограничения' },
        { order: 3,  title: 'On-demand ISR: revalidatePath и revalidateTag',    content: 'Видеоурок: On-demand ISR — revalidatePath и revalidateTag' },
        { order: 4,  title: 'Middleware: сложные сценарии авторизации',         content: 'Видеоурок: Middleware — сложные сценарии авторизации' },
        { order: 5,  title: 'Квиз: Next.js продакшен',                        content: 'Проверь себя: Next.js продакшен' },
        { order: 6,  title: 'Core Web Vitals: LCP, CLS, FID оптимизация',      content: 'Видеоурок: Core Web Vitals — LCP, CLS, FID оптимизация' },
        { order: 7,  title: 'Internationalization (i18n) в App Router',         content: 'Видеоурок: Internationalization (i18n) в App Router' },
        { order: 8,  title: 'OpenTelemetry: трейсинг Next.js приложения',       content: 'Видеоурок: OpenTelemetry — трейсинг Next.js приложения' },
        { order: 9,  title: 'Self-hosted деплой: standalone output',            content: 'Видеоурок: Self-hosted деплой — standalone output' },
        { order: 10, title: 'Задание: продакшен деплой с мониторингом',         content: 'Задание: разверни Next.js приложение на продакшен с мониторингом' },
      ],
    },
    {
      title: 'Тестирование: E2E, интеграционные и unit тесты',
      description: 'Полная тест-пирамида для fullstack приложений: Jest, Supertest для API, Playwright для E2E, моки, фикстуры и TDD подход.',
      lessons: [
        { order: 1,  title: 'Тест-пирамида: unit, integration, E2E',           content: 'Видеоурок: Тест-пирамида — unit, integration, E2E' },
        { order: 2,  title: 'Jest: настройка, matchers, coverage',              content: 'Видеоурок: Jest — настройка, matchers, coverage' },
        { order: 3,  title: 'Моки и стабы: jest.mock, spyOn',                  content: 'Видеоурок: Моки и стабы — jest.mock, spyOn' },
        { order: 4,  title: 'Тестирование NestJS сервисов и контроллеров',      content: 'Видеоурок: Тестирование NestJS сервисов и контроллеров' },
        { order: 5,  title: 'Квиз: стратегии тестирования',                   content: 'Проверь себя: стратегии тестирования' },
        { order: 6,  title: 'Supertest: интеграционные тесты API',             content: 'Видеоурок: Supertest — интеграционные тесты API' },
        { order: 7,  title: 'Playwright: E2E тесты браузера',                  content: 'Видеоурок: Playwright — E2E тесты браузера' },
        { order: 8,  title: 'TDD: разработка через тесты на практике',         content: 'Видеоурок: TDD — разработка через тесты на практике' },
        { order: 9,  title: 'Test fixtures и фабрики данных',                  content: 'Видеоурок: Test fixtures и фабрики данных' },
        { order: 10, title: 'Задание: покрыть тестами ProctoLearn API на 80%', content: 'Задание: покрой тестами ProctoLearn API на 80% с помощью Jest и Supertest' },
      ],
    },
    {
      title: 'React Native: нативные модули и публикация',
      description: 'Продвинутая разработка приложений: нативные модули на Kotlin/Swift, анимации с Reanimated, публикация в App Store и Google Play, CI/CD для мобайла.',
      lessons: [
        { order: 1,  title: 'Архитектура React Native: JSI и новая архитектура', content: 'Видеоурок: Архитектура React Native — JSI и новая архитектура' },
        { order: 2,  title: 'Нативные модули: Kotlin (Android)',                content: 'Видеоурок: Нативные модули — Kotlin (Android)' },
        { order: 3,  title: 'Нативные модули: Swift (iOS)',                     content: 'Видеоурок: Нативные модули — Swift (iOS)' },
        { order: 4,  title: 'React Native Reanimated: плавные анимации',        content: 'Видеоурок: React Native Reanimated — плавные анимации' },
        { order: 5,  title: 'Квиз: нативная разработка',                       content: 'Проверь себя: нативная разработка' },
        { order: 6,  title: 'Gesture Handler: жесты и свайпы',                 content: 'Видеоурок: Gesture Handler — жесты и свайпы' },
        { order: 7,  title: 'Performance: Hermes, Flipper, профилирование',     content: 'Видеоурок: Performance — Hermes, Flipper, профилирование' },
        { order: 8,  title: 'Публикация в Google Play: signing и release',      content: 'Видеоурок: Публикация в Google Play — signing и release' },
        { order: 9,  title: 'Публикация в App Store: сертификаты и TestFlight', content: 'Видеоурок: Публикация в App Store — сертификаты и TestFlight' },
        { order: 10, title: 'CI/CD для React Native через Fastlane',            content: 'Видеоурок: CI/CD для React Native через Fastlane' },
        { order: 11, title: 'Задание: опубликовать приложение в обоих сторах',  content: 'Задание: опубликуй приложение в Google Play и App Store' },
      ],
    },
    {
      title: 'Мониторинг и observability продакшен систем',
      description: 'Построение полной системы observability: логирование с Winston/ELK, метрики через Prometheus, трейсинг с Jaeger и алертинг через Grafana.',
      lessons: [
        { order: 1,  title: 'Три столпа observability: logs, metrics, traces',  content: 'Видеоурок: Три столпа observability — logs, metrics, traces' },
        { order: 2,  title: 'Структурированное логирование: Winston + JSON',     content: 'Видеоурок: Структурированное логирование — Winston + JSON' },
        { order: 3,  title: 'ELK Stack: Elasticsearch, Logstash, Kibana',       content: 'Видеоурок: ELK Stack — Elasticsearch, Logstash, Kibana' },
        { order: 4,  title: 'Prometheus: метрики и PromQL запросы',             content: 'Видеоурок: Prometheus — метрики и PromQL запросы' },
        { order: 5,  title: 'Квиз: observability инструменты',                 content: 'Проверь себя: observability инструменты' },
        { order: 6,  title: 'Grafana: дашборды и визуализация метрик',          content: 'Видеоурок: Grafana — дашборды и визуализация метрик' },
        { order: 7,  title: 'Alertmanager: настройка алертов в Slack',          content: 'Видеоурок: Alertmanager — настройка алертов в Slack' },
        { order: 8,  title: 'Jaeger: распределённый трейсинг',                 content: 'Видеоурок: Jaeger — распределённый трейсинг' },
        { order: 9,  title: 'OpenTelemetry: унификация инструментов',           content: 'Видеоурок: OpenTelemetry — унификация инструментов' },
        { order: 10, title: 'Задание: настроить полный observability стек',     content: 'Задание: настрой полный observability стек для продакшен приложения' },
      ],
    },
    {
      title: 'GraphQL: продвинутый API дизайн',
      description: 'GraphQL от основ до продакшена: схема, резолверы, DataLoader, подписки, федерация и интеграция с NestJS и Next.js.',
      lessons: [
        { order: 1,  title: 'GraphQL vs REST: когда использовать',              content: 'Видеоурок: GraphQL vs REST — когда использовать' },
        { order: 2,  title: 'Schema Definition Language: типы и поля',          content: 'Видеоурок: Schema Definition Language — типы и поля' },
        { order: 3,  title: 'Резолверы: Query, Mutation, Subscription',         content: 'Видеоурок: Резолверы — Query, Mutation, Subscription' },
        { order: 4,  title: 'N+1 проблема и DataLoader',                       content: 'Видеоурок: N+1 проблема и DataLoader' },
        { order: 5,  title: 'Квиз: GraphQL архитектура',                      content: 'Проверь себя: GraphQL архитектура' },
        { order: 6,  title: 'Аутентификация и авторизация в GraphQL',          content: 'Видеоурок: Аутентификация и авторизация в GraphQL' },
        { order: 7,  title: 'NestJS + GraphQL: code-first подход',             content: 'Видеоурок: NestJS + GraphQL — code-first подход' },
        { order: 8,  title: 'Apollo Client в Next.js',                         content: 'Видеоурок: Apollo Client в Next.js' },
        { order: 9,  title: 'Schema Federation: объединение микросервисов',     content: 'Видеоурок: Schema Federation — объединение микросервисов' },
        { order: 10, title: 'Читать: GraphQL Best Practices',                  content: 'Материал для чтения: GraphQL Best Practices' },
        { order: 11, title: 'Задание: GraphQL API для ProctoLearn',             content: 'Задание: реализуй GraphQL API для ProctoLearn' },
      ],
    },
  ];

  for (const courseData of coursesData) {
    // Check if course already exists to avoid duplicates
    const existing = await prisma.course.findFirst({ where: { title: courseData.title } });
    if (existing) {
      console.log(`  Қалдырылды (бар): ${courseData.title}`);
      continue;
    }

    const course = await prisma.course.create({
      data: {
        title: courseData.title,
        description: courseData.description,
        teacherId: teacher.id,
      },
    });

    for (const lesson of courseData.lessons) {
      await prisma.lesson.create({
        data: {
          courseId: course.id,
          title: lesson.title,
          content: lesson.content,
          order: lesson.order,
        },
      });
    }

    console.log(`  ✓ ${course.title} (${courseData.lessons.length} сабақ)`);
  }

  console.log('Деректер сәтті жүктелді!');
}

main().catch(console.error).finally(() => prisma.$disconnect());