FROM node:22-alpine
WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .
RUN ./node_modules/.bin/prisma generate

EXPOSE 4000
CMD ["/bin/sh", "-c", "node_modules/.bin/prisma db push --accept-data-loss && npm run start:dev"]
