FROM node:22-alpine
RUN apk add --no-cache font-liberation fontconfig
WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .
RUN ./node_modules/.bin/prisma generate

EXPOSE 4000
CMD ["/bin/sh", "-c", "node_modules/.bin/prisma db push --skip-generate && node_modules/.bin/prisma generate && npm run start:dev"]
