FROM node:24-alpine
RUN apk add --no-cache openssl font-liberation fontconfig
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY --chown=node:node . .
RUN node_modules/.bin/prisma generate && chown -R node:node /app
USER node

EXPOSE 4000
ENTRYPOINT ["/bin/sh", "/app/docker/entrypoint.sh"]
CMD ["node", "node_modules/@nestjs/cli/bin/nest.js", "start", "--watch"]
