events { worker_connections 1024; }

http {
  server {
    listen 80;
    location / {
      return 200 'Nginx OK';
      add_header Content-Type text/plain;
    }
  }

  server {
    listen 8080;
    location /stub_status {
      stub_status on;
      allow 127.0.0.1;
      allow 172.0.0.0/8;
      deny all;
    }
  }
}
